version: "3.8"

services:
  main:
    build:
      context: .
      dockerfile: ./containers/main/Dockerfile
    # container_name: main-container
    volumes:
      # bind vscode workspace root path to container target
      - type: bind
        source: ../ # path of host
        target: /workspace # path of container
        consistency: cached # apply file caching
    command: tail -f /dev/null # keep container running
